In [1]:
import pandas as pf
from pandas import Series, DataFrame

ww2_case = Series([870000, 430000, 3000000, 210000, 400000], index=['USSR', 'Germany', 'China', 'Japan', 'USA'])
ww2_dict = ww2_case.to_dict()

In [2]:
countries = ['Argentina', 'USSR', 'Germany', 'China', 'Japan', 'USA']
obj = dict(zip(countries,ww2_dict.values()))

In [3]:
print(obj)

{'Argentina': 870000, 'USSR': 430000, 'Germany': 3000000, 'China': 210000, 'Japan': 400000}

In [4]:
ww2_series = Series(obj)

In [5]:
print(ww2_series)

Argentina     870000
USSR          430000
Germany      3000000
China         210000
Japan         400000
dtype: int64

In [6]:
print(ww2_series + obj)

TypeError: unsupported operand type(s) for +: 'int' and 'dict'

In [7]:
print(ww2_case+ww2_series)

Argentina          NaN
China        3210000.0
Germany      3430000.0
Japan         610000.0
USA                NaN
USSR         1300000.0
dtype: float64

In [8]:
import pandas as pd

In [9]:
df = pd.read_csv("Automobile_data.csv")

In [10]:
print(df)

     symboling normalized-losses         make fuel-type aspiration  \
0            3                 ?  alfa-romero       gas        std
1            3                 ?  alfa-romero       gas        std
2            1                 ?  alfa-romero       gas        std
3            2               164         audi       gas        std
4            2               164         audi       gas        std
5            2                 ?         audi       gas        std
6            1               158         audi       gas        std
7            1                 ?         audi       gas        std
8            1               158         audi       gas      turbo
9            0                 ?         audi       gas      turbo
10           2               192          bmw       gas        std
11           0               192          bmw       gas        std
12           0               188          bmw       gas        std
13           0               188          bmw       gas        std
14           1                 ?          bmw       gas        std
15           0                 ?          bmw       gas        std
16           0                 ?          bmw       gas        std
17           0                 ?          bmw       gas        std
18           2               121    chevrolet       gas        std
19           1                98    chevrolet       gas        std
20           0                81    chevrolet       gas        std
21           1               118        dodge       gas        std
22           1               118        dodge       gas        std
23           1               118        dodge       gas      turbo
24           1               148        dodge       gas        std
25           1               148        dodge       gas        std
26           1               148        dodge       gas        std
27           1               148        dodge       gas      turbo
28          -1               110        dodge       gas        std
29           3               145        dodge       gas      turbo
..         ...               ...          ...       ...        ...
175         -1                65       toyota       gas        std
176         -1                65       toyota       gas        std
177         -1                65       toyota       gas        std
178          3               197       toyota       gas        std
179          3               197       toyota       gas        std
180         -1                90       toyota       gas        std
181         -1                 ?       toyota       gas        std
182          2               122   volkswagen    diesel        std
183          2               122   volkswagen       gas        std
184          2                94   volkswagen    diesel        std
185          2                94   volkswagen       gas        std
186          2                94   volkswagen       gas        std
187          2                94   volkswagen    diesel      turbo
188          2                94   volkswagen       gas        std
189          3                 ?   volkswagen       gas        std
190          3               256   volkswagen       gas        std
191          0                 ?   volkswagen       gas        std
192          0                 ?   volkswagen    diesel      turbo
193          0                 ?   volkswagen       gas        std
194         -2               103        volvo       gas        std
195         -1                74        volvo       gas        std
196         -2               103        volvo       gas        std
197         -1                74        volvo       gas        std
198         -2               103        volvo       gas      turbo
199         -1                74        volvo       gas      turbo
200         -1                95        volvo       gas        std
201         -1                95        volvo       gas      turbo
202         -1                95        volvo       gas        std
203         -1                95        volvo    diesel      turbo
204         -1                95        volvo       gas      turbo

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...    \
0            two  convertible          rwd           front        88.6  ...
1            two  convertible          rwd           front        88.6  ...
2            two    hatchback          rwd           front        94.5  ...
3           four        sedan          fwd           front        99.8  ...
4           four        sedan          4wd           front        99.4  ...
5            two        sedan          fwd           front        99.8  ...
6           four        sedan          fwd           front       105.8  ...
7           four        wagon          fwd           front       105.8  ...
8           four        sedan          fwd           front       105.8  ...
9            two    hatchback          4wd           front        99.5  ...
10           two        sedan          rwd           front       101.2  ...
11          four        sedan          rwd           front       101.2  ...
12           two        sedan          rwd           front       101.2  ...
13          four        sedan          rwd           front       101.2  ...
14          four        sedan          rwd           front       103.5  ...
15          four        sedan          rwd           front       103.5  ...
16           two        sedan          rwd           front       103.5  ...
17          four        sedan          rwd           front       110.0  ...
18           two    hatchback          fwd           front        88.4  ...
19           two    hatchback          fwd           front        94.5  ...
20          four        sedan          fwd           front        94.5  ...
21           two    hatchback          fwd           front        93.7  ...
22           two    hatchback          fwd           front        93.7  ...
23           two    hatchback          fwd           front        93.7  ...
24          four    hatchback          fwd           front        93.7  ...
25          four        sedan          fwd           front        93.7  ...
26          four        sedan          fwd           front        93.7  ...
27             ?        sedan          fwd           front        93.7  ...
28          four        wagon          fwd           front       103.3  ...
29           two    hatchback          fwd           front        95.9  ...
..           ...          ...          ...             ...         ...  ...
175         four    hatchback          fwd           front       102.4  ...
176         four        sedan          fwd           front       102.4  ...
177         four    hatchback          fwd           front       102.4  ...
178          two    hatchback          rwd           front       102.9  ...
179          two    hatchback          rwd           front       102.9  ...
180         four        sedan          rwd           front       104.5  ...
181         four        wagon          rwd           front       104.5  ...
182          two        sedan          fwd           front        97.3  ...
183          two        sedan          fwd           front        97.3  ...
184         four        sedan          fwd           front        97.3  ...
185         four        sedan          fwd           front        97.3  ...
186         four        sedan          fwd           front        97.3  ...
187         four        sedan          fwd           front        97.3  ...
188         four        sedan          fwd           front        97.3  ...
189          two  convertible          fwd           front        94.5  ...
190          two    hatchback          fwd           front        94.5  ...
191         four        sedan          fwd           front       100.4  ...
192         four        sedan          fwd           front       100.4  ...
193         four        wagon          fwd           front       100.4  ...
194         four        sedan          rwd           front       104.3  ...
195         four        wagon          rwd           front       104.3  ...
196         four        sedan          rwd           front       104.3  ...
197         four        wagon          rwd           front       104.3  ...
198         four        sedan          rwd           front       104.3  ...
199         four        wagon          rwd           front       104.3  ...
200         four        sedan          rwd           front       109.1  ...
201         four        sedan          rwd           front       109.1  ...
202         four        sedan          rwd           front       109.1  ...
203         four        sedan          rwd           front       109.1  ...
204         four        sedan          rwd           front       109.1  ...

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68              9.00        111
1            130         mpfi  3.47    2.68              9.00        111
2            152         mpfi  2.68    3.47              9.00        154
3            109         mpfi  3.19     3.4             10.00        102
4            136         mpfi  3.19     3.4              8.00        115
5            136         mpfi  3.19     3.4              8.50        110
6            136         mpfi  3.19     3.4              8.50        110
7            136         mpfi  3.19     3.4              8.50        110
8            131         mpfi  3.13     3.4              8.30        140
9            131         mpfi  3.13     3.4              7.00        160
10           108         mpfi   3.5     2.8              8.80        101
11           108         mpfi   3.5     2.8              8.80        101
12           164         mpfi  3.31    3.19              9.00        121
13           164         mpfi  3.31    3.19              9.00        121
14           164         mpfi  3.31    3.19              9.00        121
15           209         mpfi  3.62    3.39              8.00        182
16           209         mpfi  3.62    3.39              8.00        182
17           209         mpfi  3.62    3.39              8.00        182
18            61         2bbl  2.91    3.03              9.50         48
19            90         2bbl  3.03    3.11              9.60         70
20            90         2bbl  3.03    3.11              9.60         70
21            90         2bbl  2.97    3.23              9.41         68
22            90         2bbl  2.97    3.23              9.40         68
23            98         mpfi  3.03    3.39              7.60        102
24            90         2bbl  2.97    3.23              9.40         68
25            90         2bbl  2.97    3.23              9.40         68
26            90         2bbl  2.97    3.23              9.40         68
27            98         mpfi  3.03    3.39              7.60        102
28           122         2bbl  3.34    3.46              8.50         88
29           156          mfi   3.6     3.9              7.00        145
..           ...          ...   ...     ...               ...        ...
175          122         mpfi  3.31    3.54              8.70         92
176          122         mpfi  3.31    3.54              8.70         92
177          122         mpfi  3.31    3.54              8.70         92
178          171         mpfi  3.27    3.35              9.30        161
179          171         mpfi  3.27    3.35              9.30        161
180          171         mpfi  3.27    3.35              9.20        156
181          161         mpfi  3.27    3.35              9.20        156
182           97          idi  3.01     3.4             23.00         52
183          109         mpfi  3.19     3.4              9.00         85
184           97          idi  3.01     3.4             23.00         52
185          109         mpfi  3.19     3.4              9.00         85
186          109         mpfi  3.19     3.4              9.00         85
187           97          idi  3.01     3.4             23.00         68
188          109         mpfi  3.19     3.4             10.00        100
189          109         mpfi  3.19     3.4              8.50         90
190          109         mpfi  3.19     3.4              8.50         90
191          136         mpfi  3.19     3.4              8.50        110
192           97          idi  3.01     3.4             23.00         68
193          109         mpfi  3.19     3.4              9.00         88
194          141         mpfi  3.78    3.15              9.50        114
195          141         mpfi  3.78    3.15              9.50        114
196          141         mpfi  3.78    3.15              9.50        114
197          141         mpfi  3.78    3.15              9.50        114
198          130         mpfi  3.62    3.15              7.50        162
199          130         mpfi  3.62    3.15              7.50        162
200          141         mpfi  3.78    3.15              9.50        114
201          141         mpfi  3.78    3.15              8.70        160
202          173         mpfi  3.58    2.87              8.80        134
203          145          idi  3.01     3.4             23.00        106
204          141         mpfi  3.78    3.15              9.50        114

     peak-rpm city-mpg highway-mpg  price
0        5000       21          27  13495
1        5000       21          27  16500
2        5000       19          26  16500
3        5500       24          30  13950
4        5500       18          22  17450
5        5500       19          25  15250
6        5500       19          25  17710
7        5500       19          25  18920
8        5500       17          20  23875
9        5500       16          22      ?
10       5800       23          29  16430
11       5800       23          29  16925
12       4250       21          28  20970
13       4250       21          28  21105
14       4250       20          25  24565
15       5400       16          22  30760
16       5400       16          22  41315
17       5400       15          20  36880
18       5100       47          53   5151
19       5400       38          43   6295
20       5400       38          43   6575
21       5500       37          41   5572
22       5500       31          38   6377
23       5500       24          30   7957
24       5500       31          38   6229
25       5500       31          38   6692
26       5500       31          38   7609
27       5500       24          30   8558
28       5000       24          30   8921
29       5000       19          24  12964
..        ...      ...         ...    ...
175      4200       27          32   9988
176      4200       27          32  10898
177      4200       27          32  11248
178      5200       20          24  16558
179      5200       19          24  15998
180      5200       20          24  15690
181      5200       19          24  15750
182      4800       37          46   7775
183      5250       27          34   7975
184      4800       37          46   7995
185      5250       27          34   8195
186      5250       27          34   8495
187      4500       37          42   9495
188      5500       26          32   9995
189      5500       24          29  11595
190      5500       24          29   9980
191      5500       19          24  13295
192      4500       33          38  13845
193      5500       25          31  12290
194      5400       23          28  12940
195      5400       23          28  13415
196      5400       24          28  15985
197      5400       24          28  16515
198      5100       17          22  18420
199      5100       17          22  18950
200      5400       23          28  16845
201      5300       19          25  19045
202      5500       18          23  21485
203      4800       26          27  22470
204      5400       19          25  22625

[205 rows x 26 columns]

In [47]:
print(df.groupby(['make']).first())

               symboling normalized-losses fuel-type aspiration num-of-doors  \
make
alfa-romero            3                 ?       gas        std          two
audi                   2               164       gas        std         four
bmw                    2               192       gas        std          two
chevrolet              2               121       gas        std          two
dodge                  1               118       gas        std          two
honda                  2               137       gas        std          two
isuzu                  0                 ?       gas        std         four
jaguar                 0               145       gas        std         four
mazda                  1               104       gas        std          two
mercedes-benz         -1                93    diesel      turbo         four
mercury                1                 ?       gas      turbo          two
mitsubishi             2               161       gas        std          two
nissan                 1               128       gas        std          two
peugot                 0               161       gas        std         four
plymouth               1               119       gas        std          two
porsche                3               186       gas        std          two
renault                0                 ?       gas        std         four
saab                   3               150       gas        std          two
subaru                 2                83       gas        std          two
toyota                 1                87       gas        std          two
volkswagen             2               122    diesel        std          two
volvo                 -2               103       gas        std         four

                body-style drive-wheels engine-location  wheel-base  length  \
make
alfa-romero    convertible          rwd           front        88.6   168.8
audi                 sedan          fwd           front        99.8   176.6
bmw                  sedan          rwd           front       101.2   176.8
chevrolet        hatchback          fwd           front        88.4   141.1
dodge            hatchback          fwd           front        93.7   157.3
honda            hatchback          fwd           front        86.6   144.6
isuzu                sedan          rwd           front        94.3   170.7
jaguar               sedan          rwd           front       113.0   199.6
mazda            hatchback          fwd           front        93.1   159.1
mercedes-benz        sedan          rwd           front       110.0   190.9
mercury          hatchback          rwd           front       102.7   178.4
mitsubishi       hatchback          fwd           front        93.7   157.3
nissan               sedan          fwd           front        94.5   165.3
peugot               sedan          rwd           front       107.9   186.7
plymouth         hatchback          fwd           front        93.7   157.3
porsche          hatchback          rwd           front        94.5   168.9
renault              wagon          fwd           front        96.1   181.5
saab             hatchback          fwd           front        99.1   186.6
subaru           hatchback          fwd           front        93.7   156.9
toyota           hatchback          fwd           front        95.7   158.7
volkswagen           sedan          fwd           front        97.3   171.7
volvo                sedan          rwd           front       104.3   188.8

               ...    engine-size  fuel-system  bore stroke compression-ratio  \
make           ...
alfa-romero    ...            130         mpfi  3.47   2.68              9.00
audi           ...            109         mpfi  3.19    3.4             10.00
bmw            ...            108         mpfi   3.5    2.8              8.80
chevrolet      ...             61         2bbl  2.91   3.03              9.50
dodge          ...             90         2bbl  2.97   3.23              9.41
honda          ...             92         1bbl  2.91   3.41              9.60
isuzu          ...            111         2bbl  3.31   3.23              8.50
jaguar         ...            258         mpfi  3.63   4.17              8.10
mazda          ...             91         2bbl  3.03   3.15              9.00
mercedes-benz  ...            183          idi  3.58   3.64             21.50
mercury        ...            140         mpfi  3.78   3.12              8.00
mitsubishi     ...             92         2bbl  2.97   3.23              9.40
nissan         ...             97         2bbl  3.15   3.29              9.40
peugot         ...            120         mpfi  3.46   3.19              8.40
plymouth       ...             90         2bbl  2.97   3.23              9.40
porsche        ...            151         mpfi  3.94   3.11              9.50
renault        ...            132         mpfi  3.46    3.9              8.70
saab           ...            121         mpfi  3.54   3.07              9.31
subaru         ...             97         2bbl  3.62   2.36              9.00
toyota         ...             92         2bbl  3.05   3.03              9.00
volkswagen     ...             97          idi  3.01    3.4             23.00
volvo          ...            141         mpfi  3.78   3.15              9.50

               horsepower peak-rpm city-mpg highway-mpg  price
make
alfa-romero           111     5000       21          27  13495
audi                  102     5500       24          30  13950
bmw                   101     5800       23          29  16430
chevrolet              48     5100       47          53   5151
dodge                  68     5500       37          41   5572
honda                  58     4800       49          54   6479
isuzu                  78     4800       24          29   6785
jaguar                176     4750       15          19  32250
mazda                  68     5000       30          31   5195
mercedes-benz         123     4350       22          25  25552
mercury               175     5000       19          24  16503
mitsubishi             68     5500       37          41   5389
nissan                 69     5200       31          37   5499
peugot                 97     5000       19          24  11900
plymouth               68     5500       37          41   5572
porsche               143     5500       19          27  22018
renault                 ?        ?       23          31   9295
saab                  110     5250       21          28  11850
subaru                 69     4900       31          36   5118
toyota                 62     4800       35          39   5348
volkswagen             52     4800       37          46   7775
volvo                 114     5400       23          28  12940

[22 rows x 25 columns]

In [83]:
dm = df['make'].groupby('make').count()

KeyError: 'make'

In [77]:
print(df[['make']].count().make)

205

In [26]:
print(df.price.sum())

134951650016500139501745015250177101892023875?1643016925209702110524565307604131536880515162956575557263777957622966927609855889211296464796855539965297129729572957895909588451029512945103456785??11048322503555036000519560956795669573951094511845136451564588458495105951024510795112451828018344255522824828176316003418435056409604540016503538961896669768999598499126291486914489698981899279927954997099664968497349729977997499799982498949954913499143991349917199196991839911900132001244013860155801690016695170751663017950181505572795762296692760989211276422018325283402837028?9295989511850121701504015510181501862051187053760371267775996092331125974631019880131169453486338648869187898877869387198789877887738835892588058823892989538844996399989111991154917669894810698998810898112481655815998156901575077757975799581958495949599951159599801329513845122901294013415159851651518420189501684519045214852247022625

In [43]:
print(df.groupby(['make','price']).max())

                   symboling normalized-losses fuel-type aspiration  \
make        price
alfa-romero 13495          3                 ?       gas        std
            16500          3                 ?       gas        std
audi        13950          2               164       gas        std
            15250          2                 ?       gas        std
            17450          2               164       gas        std
            17710          1               158       gas        std
            18920          1                 ?       gas        std
            23875          1               158       gas      turbo
            ?              0                 ?       gas      turbo
bmw         16430          2               192       gas        std
            16925          0               192       gas        std
            20970          0               188       gas        std
            21105          0               188       gas        std
            24565          1                 ?       gas        std
            30760          0                 ?       gas        std
            36880          0                 ?       gas        std
            41315          0                 ?       gas        std
chevrolet   5151           2               121       gas        std
            6295           1                98       gas        std
            6575           0                81       gas        std
dodge       12964          3               145       gas      turbo
            5572           1               118       gas        std
            6229           1               148       gas        std
            6377           1               118       gas        std
            6692           1               148       gas        std
            7609           1               148       gas        std
            7957           1               118       gas      turbo
            8558           1               148       gas      turbo
            8921          -1               110       gas        std
honda       10295          0                85       gas        std
...                      ...               ...       ...        ...
toyota      8948          -1                65       gas        std
            9258           0                91       gas        std
            9298           1               168       gas        std
            9538           1               168       gas        std
            9639           2               134       gas        std
            9988          -1                65       gas        std
            9989           2               134       gas        std
volkswagen  11595          3                 ?       gas        std
            12290          0                 ?       gas        std
            13295          0                 ?       gas        std
            13845          0                 ?    diesel      turbo
            7775           2               122    diesel        std
            7975           2               122       gas        std
            7995           2                94    diesel        std
            8195           2                94       gas        std
            8495           2                94       gas        std
            9495           2                94    diesel      turbo
            9980           3               256       gas        std
            9995           2                94       gas        std
volvo       12940         -2               103       gas        std
            13415         -1                74       gas        std
            15985         -2               103       gas        std
            16515         -1                74       gas        std
            16845         -1                95       gas        std
            18420         -2               103       gas      turbo
            18950         -1                74       gas      turbo
            19045         -1                95       gas      turbo
            21485         -1                95       gas        std
            22470         -1                95    diesel      turbo
            22625         -1                95       gas      turbo

                  num-of-doors   body-style drive-wheels engine-location  \
make        price
alfa-romero 13495          two  convertible          rwd           front
            16500          two    hatchback          rwd           front
audi        13950         four        sedan          fwd           front
            15250          two        sedan          fwd           front
            17450         four        sedan          4wd           front
            17710         four        sedan          fwd           front
            18920         four        wagon          fwd           front
            23875         four        sedan          fwd           front
            ?              two    hatchback          4wd           front
bmw         16430          two        sedan          rwd           front
            16925         four        sedan          rwd           front
            20970          two        sedan          rwd           front
            21105         four        sedan          rwd           front
            24565         four        sedan          rwd           front
            30760         four        sedan          rwd           front
            36880         four        sedan          rwd           front
            41315          two        sedan          rwd           front
chevrolet   5151           two    hatchback          fwd           front
            6295           two    hatchback          fwd           front
            6575          four        sedan          fwd           front
dodge       12964          two    hatchback          fwd           front
            5572           two    hatchback          fwd           front
            6229          four    hatchback          fwd           front
            6377           two    hatchback          fwd           front
            6692          four        sedan          fwd           front
            7609          four        sedan          fwd           front
            7957           two    hatchback          fwd           front
            8558             ?        sedan          fwd           front
            8921          four        wagon          fwd           front
honda       10295         four        sedan          fwd           front
...                        ...          ...          ...             ...
toyota      8948          four        sedan          fwd           front
            9258          four        sedan          fwd           front
            9298           two        sedan          rwd           front
            9538           two    hatchback          rwd           front
            9639           two      hardtop          rwd           front
            9988          four    hatchback          fwd           front
            9989           two    hatchback          rwd           front
volkswagen  11595          two  convertible          fwd           front
            12290         four        wagon          fwd           front
            13295         four        sedan          fwd           front
            13845         four        sedan          fwd           front
            7775           two        sedan          fwd           front
            7975           two        sedan          fwd           front
            7995          four        sedan          fwd           front
            8195          four        sedan          fwd           front
            8495          four        sedan          fwd           front
            9495          four        sedan          fwd           front
            9980           two    hatchback          fwd           front
            9995          four        sedan          fwd           front
volvo       12940         four        sedan          rwd           front
            13415         four        wagon          rwd           front
            15985         four        sedan          rwd           front
            16515         four        wagon          rwd           front
            16845         four        sedan          rwd           front
            18420         four        sedan          rwd           front
            18950         four        wagon          rwd           front
            19045         four        sedan          rwd           front
            21485         four        sedan          rwd           front
            22470         four        sedan          rwd           front
            22625         four        sedan          rwd           front

                   wheel-base  length     ...       num-of-cylinders  \
make        price                         ...
alfa-romero 13495        88.6   168.8     ...                   four
            16500        94.5   171.2     ...                    six
audi        13950        99.8   176.6     ...                   four
            15250        99.8   177.3     ...                   five
            17450        99.4   176.6     ...                   five
            17710       105.8   192.7     ...                   five
            18920       105.8   192.7     ...                   five
            23875       105.8   192.7     ...                   five
            ?            99.5   178.2     ...                   five
bmw         16430       101.2   176.8     ...                   four
            16925       101.2   176.8     ...                   four
            20970       101.2   176.8     ...                    six
            21105       101.2   176.8     ...                    six
            24565       103.5   189.0     ...                    six
            30760       103.5   189.0     ...                    six
            36880       110.0   197.0     ...                    six
            41315       103.5   193.8     ...                    six
chevrolet   5151         88.4   141.1     ...                  three
            6295         94.5   155.9     ...                   four
            6575         94.5   158.8     ...                   four
dodge       12964        95.9   173.2     ...                   four
            5572         93.7   157.3     ...                   four
            6229         93.7   157.3     ...                   four
            6377         93.7   157.3     ...                   four
            6692         93.7   157.3     ...                   four
            7609         93.7   157.3     ...                   four
            7957         93.7   157.3     ...                   four
            8558         93.7   157.3     ...                   four
            8921        103.3   174.6     ...                   four
honda       10295        96.5   175.4     ...                   four
...                       ...     ...     ...                    ...
toyota      8948        102.4   175.6     ...                   four
            9258         95.7   166.3     ...                   four
            9298         94.5   168.7     ...                   four
            9538         94.5   168.7     ...                   four
            9639         98.4   176.2     ...                   four
            9988        102.4   175.6     ...                   four
            9989         98.4   176.2     ...                   four
volkswagen  11595        94.5   159.3     ...                   four
            12290       100.4   183.1     ...                   four
            13295       100.4   180.2     ...                   five
            13845       100.4   180.2     ...                   four
            7775         97.3   171.7     ...                   four
            7975         97.3   171.7     ...                   four
            7995         97.3   171.7     ...                   four
            8195         97.3   171.7     ...                   four
            8495         97.3   171.7     ...                   four
            9495         97.3   171.7     ...                   four
            9980         94.5   165.7     ...                   four
            9995         97.3   171.7     ...                   four
volvo       12940       104.3   188.8     ...                   four
            13415       104.3   188.8     ...                   four
            15985       104.3   188.8     ...                   four
            16515       104.3   188.8     ...                   four
            16845       109.1   188.8     ...                   four
            18420       104.3   188.8     ...                   four
            18950       104.3   188.8     ...                   four
            19045       109.1   188.8     ...                   four
            21485       109.1   188.8     ...                    six
            22470       109.1   188.8     ...                    six
            22625       109.1   188.8     ...                   four

                   engine-size  fuel-system  bore stroke  compression-ratio  \
make        price
alfa-romero 13495          130         mpfi  3.47   2.68               9.00
            16500          152         mpfi  3.47   3.47               9.00
audi        13950          109         mpfi  3.19    3.4              10.00
            15250          136         mpfi  3.19    3.4               8.50
            17450          136         mpfi  3.19    3.4               8.00
            17710          136         mpfi  3.19    3.4               8.50
            18920          136         mpfi  3.19    3.4               8.50
            23875          131         mpfi  3.13    3.4               8.30
            ?              131         mpfi  3.13    3.4               7.00
bmw         16430          108         mpfi   3.5    2.8               8.80
            16925          108         mpfi   3.5    2.8               8.80
            20970          164         mpfi  3.31   3.19               9.00
            21105          164         mpfi  3.31   3.19               9.00
            24565          164         mpfi  3.31   3.19               9.00
            30760          209         mpfi  3.62   3.39               8.00
            36880          209         mpfi  3.62   3.39               8.00
            41315          209         mpfi  3.62   3.39               8.00
chevrolet   5151            61         2bbl  2.91   3.03               9.50
            6295            90         2bbl  3.03   3.11               9.60
            6575            90         2bbl  3.03   3.11               9.60
dodge       12964          156          mfi   3.6    3.9               7.00
            5572            90         2bbl  2.97   3.23               9.41
            6229            90         2bbl  2.97   3.23               9.40
            6377            90         2bbl  2.97   3.23               9.40
            6692            90         2bbl  2.97   3.23               9.40
            7609            90         2bbl  2.97   3.23               9.40
            7957            98         mpfi  3.03   3.39               7.60
            8558            98         mpfi  3.03   3.39               7.60
            8921           122         2bbl  3.34   3.46               8.50
honda       10295          110         1bbl  3.15   3.58               9.00
...                        ...          ...   ...    ...                ...
toyota      8948           122         mpfi  3.31   3.54               8.70
            9258            98         2bbl  3.19   3.03               9.00
            9298            98         mpfi  3.24   3.08               9.40
            9538            98         mpfi  3.24   3.08               9.40
            9639           146         mpfi  3.62    3.5               9.30
            9988           122         mpfi  3.31   3.54               8.70
            9989           146         mpfi  3.62    3.5               9.30
volkswagen  11595          109         mpfi  3.19    3.4               8.50
            12290          109         mpfi  3.19    3.4               9.00
            13295          136         mpfi  3.19    3.4               8.50
            13845           97          idi  3.01    3.4              23.00
            7775            97          idi  3.01    3.4              23.00
            7975           109         mpfi  3.19    3.4               9.00
            7995            97          idi  3.01    3.4              23.00
            8195           109         mpfi  3.19    3.4               9.00
            8495           109         mpfi  3.19    3.4               9.00
            9495            97          idi  3.01    3.4              23.00
            9980           109         mpfi  3.19    3.4               8.50
            9995           109         mpfi  3.19    3.4              10.00
volvo       12940          141         mpfi  3.78   3.15               9.50
            13415          141         mpfi  3.78   3.15               9.50
            15985          141         mpfi  3.78   3.15               9.50
            16515          141         mpfi  3.78   3.15               9.50
            16845          141         mpfi  3.78   3.15               9.50
            18420          130         mpfi  3.62   3.15               7.50
            18950          130         mpfi  3.62   3.15               7.50
            19045          141         mpfi  3.78   3.15               8.70
            21485          173         mpfi  3.58   2.87               8.80
            22470          145          idi  3.01    3.4              23.00
            22625          141         mpfi  3.78   3.15               9.50

                  horsepower peak-rpm city-mpg  highway-mpg
make        price
alfa-romero 13495        111     5000       21           27
            16500        154     5000       21           27
audi        13950        102     5500       24           30
            15250        110     5500       19           25
            17450        115     5500       18           22
            17710        110     5500       19           25
            18920        110     5500       19           25
            23875        140     5500       17           20
            ?            160     5500       16           22
bmw         16430        101     5800       23           29
            16925        101     5800       23           29
            20970        121     4250       21           28
            21105        121     4250       21           28
            24565        121     4250       20           25
            30760        182     5400       16           22
            36880        182     5400       15           20
            41315        182     5400       16           22
chevrolet   5151          48     5100       47           53
            6295          70     5400       38           43
            6575          70     5400       38           43
dodge       12964        145     5000       19           24
            5572          68     5500       37           41
            6229          68     5500       31           38
            6377          68     5500       31           38
            6692          68     5500       31           38
            7609          68     5500       31           38
            7957         102     5500       24           30
            8558         102     5500       24           30
            8921          88     5000       24           30
honda       10295         86     5800       27           33
...                      ...      ...      ...          ...
toyota      8948          92     4200       29           34
            9258          70     4800       28           34
            9298         112     6600       26           29

In [60]:
print(df.price == df['price'].max())

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9       True
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
175    False
176    False
177    False
178    False
179    False
180    False
181    False
182    False
183    False
184    False
185    False
186    False
187    False
188    False
189    False
190    False
191    False
192    False
193    False
194    False
195    False
196    False
197    False
198    False
199    False
200    False
201    False
202    False
203    False
204    False
Name: price, Length: 205, dtype: bool

In [61]:
dx=df[['make','price']][df.price == df['price'].max()]
print(dx)

        make price
9       audi     ?
44     isuzu     ?
45     isuzu     ?
129  porsche     ?

In [62]:
print(df.groupby(['make'].count()))

TypeError: count() takes exactly one argument (0 given)